### ISSUE TITLE
SinglePlayerServerSettings Mod Crash in 1.8

### ISSUE THREAD

**Issue by Luigibrine** [Elecs-Mods/SinglePlayerServerSettings#2]
My game crashed while running on Minecraft 1.8.

Here's the crash report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-Recommended.jar)
  NEICorePlugin (Not-Enough-Items-1.8-Recommended.jar)
  ElecCoreLoader (ElecCore-1.8.8-1.4.200.jar)
  CCCDeobfPlugin (unknown)
  SinglePlayerServerSettingsCore (SinglePlayerServerSettings-1.0.7.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 5/18/18 12:25 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/util/text/ITextComponent
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:334)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.text.ITextComponent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:334)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:483)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 97823464 bytes (93 MB) / 262787072 bytes (250 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1577 Optifine OptiFine_1.8_HD_U_I3 5 mods loaded, 0 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
		mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
		FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1577.jar) 
		Forge{11.14.4.1577} [Minecraft Forge] (forge-1.8-11.14.4.1577.jar) 
		CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) 
		NotEnoughItems{1.0.5.82} [Not Enough Items] (Not-Enough-Items-1.8-Recommended.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-Recommended.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NEICorePlugin (Not-Enough-Items-1.8-Recommended.jar)
  codechicken.nei.asm.NEITransformer
ElecCoreLoader (ElecCore-1.8.8-1.4.200.jar)
  elec332.core.asm.ASMLoader
CCCDeobfPlugin (unknown)
  
SinglePlayerServerSettingsCore (SinglePlayerServerSettings-1.0.7.jar)
  elec332.singleplayerserversettings.SinglePlayerServerSettingsTransformer
	GL info: ' Vendor: 'Intel' Version: '3.3.0 - Build 8.15.10.2696' Renderer: 'Intel(R) HD Graphics 4000'
	Launched Version: 1.8-forge1.8-11.14.4.1577
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 3.3.0 - Build 8.15.10.2696, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	OptiFine Version: OptiFine_1.8_HD_U_I3
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.3.0 - Build 8.15.10.2696
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by Elec332** [comment]
How are you so sure it's this mod? I cannot find any hints that this mod causes it.

**Comment by SyFizz** [comment]
@Elec332 
Hello, I think this issue is caused by SinglePlayerServerSettings because i use CurseForge to manage my mods, and if i try to launch the game with the mod enabled, the game crashes instantly, and with the mod disabled, it works pretty well
There's maybe an incompatibility with an other mod 🤔
